export const cities = [
  {
    id:'denver', name:'Denver', eyebrow:'City & County of Denver',
    intro:'A Denver remodel starts with the way you want to live—and the particular home you want to keep. Summit builds additions and renovates kitchens, bathrooms, and connected living spaces across the city.',
    focus:'Permit sequencing, existing-home systems, and historic-property questions.',
    sections:[
      ['Identify the review path before setting a start date', 'An interior update and a structural addition can follow different review paths. Denver provides separate resources for residential plan review and certain quicker permits. Describe the complete scope, including structural, electrical, plumbing, and mechanical changes, before deciding which applications are needed. Use the city’s current guidance for scheduling; a general average is not a commitment for your project.'],
      ['Look beyond the room being remodeled', 'A bungalow, a Denver Square, a ranch, and a home with earlier additions can have very different routes for new plumbing, ducts, and wiring. Gather prior plans and permit records if available. Ask what the project team needs to inspect before assuming a wall can move, a floor can carry a new load, or existing utilities can support the new layout.'],
      ['Check historic status when the exterior changes', 'If the property is locally designated or within a historic district, ask Denver Landmark Preservation whether the work needs design review. A kitchen or bathroom project can touch the exterior through a new window or exhaust outlet. Discuss those details while developing the layout rather than after cabinets or fixtures are ordered.'],
      ['Tie an addition into the site', 'A larger house changes roof area, drainage, and the relationship to the yard. Establish property boundaries and applicable zoning before relying on a sketch of the available space. Include access for construction and the protection of occupied rooms in the scope.']
    ], sources:['denver'], guides:['planning-addition','addition-timeline','older-homes','asbestos'],
    question:'Does every Denver remodel follow the same permit process?', answer:'No. The city’s review path depends on the work. Ask the permitting team to assess the full scope and any zoning or historic-review requirements for the property.'
  },
  {
    id:'arvada', name:'Arvada', eyebrow:'Arvada, Colorado',
    intro:'Make room for what comes next in your Arvada home. Summit connects additions and major renovations with the kitchen, bathroom, and access improvements that make a house easier to live in.',
    focus:'Interior permit scope, historic-area review, and private design approvals.',
    sections:[
      ['Match the plan to the home you have', 'Start with the building’s actual condition and renovation history. An older cottage may need a different approach to utilities and framing than a ranch or a recently built home. Gather records and identify the problems you want to solve. A large lot, newer construction date, or open-looking floor plan does not establish what changes are feasible.'],
      ['Use Arvada’s interior-remodel guidance', 'Arvada provides a dedicated residential interior-remodel resource. Use it to understand submittals and discuss any plan changes during construction with the project team. Decide whether the scope stays within existing rooms or includes structural work and an addition, because that distinction affects the information needed for review.'],
      ['Ask about historic and neighborhood approvals', 'For a property in or near a historic area, confirm its designation and applicable review with the city before designing exterior changes. Separately, check any recorded covenants, homeowners association rules, or design-review requirements. A municipal permit and a private association approval address different questions. Neither should be assumed to replace the other.'],
      ['Budget for the connections', 'A kitchen expansion may connect structural work to electrical service, appliance ventilation, and finishes in adjoining rooms. An addition may need drainage and utility review. Ask for those connections to be identified in the scope, then establish which selections and approvals must be resolved before construction.']
    ], sources:['arvada','arvadaPermits','address'], guides:['planning-addition','build-up-out','kitchen-cost','older-homes'],
    question:'Can I treat an HOA approval as permission to build?', answer:'No. Private design approval and municipal permitting are separate. Confirm both when they apply, including any required changes to plans.'
  },
  {
    id:'wheat-ridge', name:'Wheat Ridge', eyebrow:'Wheat Ridge, Colorado',
    intro:'Keep the character and location you value while making your Wheat Ridge home fit today’s routines. Summit helps connect larger renovations and additions with the details that make individual rooms work.',
    focus:'Existing systems, addition feasibility, and separate utility coordination.',
    sections:[
      ['Get useful information from the existing house', 'If you are remodeling a ranch or another older home, look at the renovation history as well as the year it was built. Electrical capacity, plumbing condition, ventilation routes, and prior alterations can change the scope. Treat older materials as a reason to assess the work area, not as proof that a particular problem exists.'],
      ['A generous yard is a starting point, not a building envelope', 'Before comparing an addition with a rearranged interior, establish boundaries, easements, setbacks, drainage, and how construction can reach the work area. A room that looks easy to extend on paper may connect to a roof or foundation in a more involved way. Evaluate those connections before comparing finish prices.'],
      ['Identify water and wastewater providers separately', 'The building department and utility providers may be different organizations. Locate the providers for the address and ask whether new fixtures or an expanded home require their review. Request written information about any capacity, connection, or service charges rather than assuming a building permit covers all costs.'],
      ['Use the current building-permit resources', 'Wheat Ridge’s Building Division is the starting point for the city’s current applications and inspection information. Keep the approved scope aligned with the work on site. When a bathroom or kitchen layout changes, revisit the related trade work and any revisions needed before it is concealed.']
    ], sources:['wheat','address'], guides:['whole-home-plan','older-homes','bathroom-cost','asbestos'],
    question:'Does a larger lot mean an addition will be approved?', answer:'No. The property’s zoning, easements, drainage, utilities, and construction conditions still need review. Start with property-specific information rather than lot size alone.'
  },
  {
    id:'lakewood', name:'Lakewood', eyebrow:'Lakewood, Colorado',
    intro:'A Lakewood renovation can make an established home feel ready for a new chapter. Summit works on additions, coordinated home improvements, kitchens, bathrooms, and changes for easier everyday access.',
    focus:'Current zoning, utility-provider boundaries, and whole-home coordination.',
    sections:[
      ['Confirm the rules for the proposal you are making', 'Before paying for a detailed expansion design, ask Lakewood Planning to confirm the property’s current zoning and the standards that apply to your proposed use. Older articles or saved zoning maps may not describe the rules in effect when you apply. Establish the permitted building envelope and review steps for the specific address.'],
      ['Ask who supplies water and who handles wastewater', 'Lakewood-area service can involve independent water or sanitation districts. Identify the providers using the property’s bills and official mapping resources. Adding fixtures, changing a service, or expanding the home may prompt questions from those providers. Ask each organization about its role, requirements, and any separate charges.'],
      ['Connect the remodel to the house’s existing systems', 'For a ranch, split-level, or home altered over time, consider how a new layout affects stairs, structure, plumbing, and heating or cooling. A kitchen or bathroom project is an opportunity to evaluate the systems serving that room. It is not a reason to assume every older system needs replacement.'],
      ['Look at site conditions on the west side', 'Where a project approaches foothill terrain or mapped geologic constraints, use the applicable hazard maps and qualified professional advice to assess the site. Do not infer a parcel’s conditions from the neighborhood name. An addition’s drainage and foundation plan should work with the property’s actual setting.']
    ], sources:['lakewood','address','geology'], guides:['whole-home-plan','whole-home-cost','soils','kitchen-cost'],
    question:'Is the City of Lakewood always my water provider?', answer:'No. Check the providers for your address. Water and sanitation approvals or charges can be separate from the city’s building review.'
  },
  {
    id:'morrison', name:'Morrison', eyebrow:'Morrison & its surrounding service area',
    intro:'For a Morrison-area remodel, the first useful detail is the property address. Summit helps homeowners plan additions and renovations with the site, existing home, and governing jurisdiction in view.',
    focus:'Town versus county jurisdiction, site constraints, and foothills infrastructure.',
    callout:'A Morrison mailing address does not establish that the property is inside the Town of Morrison. Check municipal status before choosing a permit checklist.',
    sections:[
      ['Start with municipal status', 'Use Jefferson County’s address lookup to check whether the parcel is incorporated or unincorporated. Then confirm the result with the relevant planning office. For a property inside the Town of Morrison, use the town’s residential and addition checklists. For an unincorporated property, begin with the county’s requirements.'],
      ['Let the site inform the addition', 'Ask whether floodplain, drainage, historic, slope, or geologic review affects the proposed work. For property near Bear Creek or foothill terrain, establish the parcel’s mapped conditions before fixing a finished-floor elevation or excavating. A map is a screening tool; the permitting authority and design professionals determine what the project needs.'],
      ['Review wildfire applicability for county properties', 'Jefferson County’s wildfire requirements apply to covered work in its unincorporated wildland-urban interface. Check the map and proposed scope before drawing conclusions. Interior-only alterations are treated differently from additions or exterior work; the county’s current guidance explains those distinctions.'],
      ['Check water, wastewater, and access early', 'Determine whether the property uses district water and sewer or a well and on-site wastewater system. Discuss additional rooms or fixtures with the responsible provider or authority. Delivery access, equipment staging, snow exposure, and occupied-home access also belong in the planning conversation. They can affect how construction is sequenced even when the room layout is straightforward.']
    ], sources:['address','morrison','wildfire','geology'], guides:['jeffco','soils','planning-addition','bathroom-cost'],
    question:'Does the Jefferson County wildfire code apply to every Morrison address?', answer:'No. Municipal status, the county’s mapped WUI boundary, and the work being proposed determine applicability. It is not a blanket rule for every home with a Morrison mailing address.'
  },
  {
    id:'golden', name:'Golden', eyebrow:'Golden, Colorado',
    intro:'A Golden remodel should respect the home you value and the setting around it. Summit brings additions, whole-home changes, kitchens, and bathrooms into a construction plan that begins with the right property questions.',
    focus:'Municipal boundaries, historic designation, and foundation planning.',
    callout:'Check municipal status and historic designation before designing exterior changes. A Golden postal address and a home’s age are useful clues, not final determinations.',
    sections:[
      ['Confirm whether the property is inside Golden', 'Jefferson County’s address lookup identifies municipal status. Use that result to establish whether Golden or the county is the starting point for permitting. Do not apply unincorporated county rules to a city property, or assume city rules apply simply because “Golden” appears in the mailing address.'],
      ['Check designation rather than assuming what “historic” means', 'Golden has a formal historic-preservation code. Before changing a designated building or a property in a protected district, ask the city which review applies. A rear addition can still alter the building’s historic character. A home being more than 50 years old does not, by itself, prove it is designated or that a particular hearing is required.'],
      ['Coordinate preservation, zoning, and construction', 'If preservation review applies, ask how it relates to the zoning and building approvals for your project. Resolve the proposed massing, openings, materials, and visible equipment with the design team before ordering items that may need to change. An interior kitchen or bath project should still consider whether new ventilation or windows affect the exterior.'],
      ['Assess the ground as carefully as the floor plan', 'The county publishes information about dipping bedrock and other geologic hazards. Use maps to identify questions for a site-specific assessment; they are not a diagnosis for a whole city. For an addition, discuss excavation, foundations, roof runoff, and drainage with the appropriate professionals. Changes to the yard can matter to the building as well.']
    ], sources:['address','golden','geology','ddba'], guides:['soils','jeffco','build-up-out','kitchen-cost'],
    question:'Does a 50-year-old Golden home automatically need a public hearing?', answer:'No. Age alone does not establish designation or the review path. Ask Golden Planning about the actual property and proposed scope.'
  }
].map(c=>({...c,path:`/service-areas/${c.id}-co/`, title:`${c.name}, CO Home Remodeling | Summit Custom Builders`, description:`Plan home additions, major remodels, kitchens, and bathrooms in ${c.name}, CO. Explore local planning considerations and talk with Summit Custom Builders.`}));
export const cityById=Object.fromEntries(cities.map(c=>[c.id,c]));

export const localServices = [
  {service:'additions',city:'arvada',path:'/home-addition-arvada-co/',
    description:'Plan a home addition in Arvada, CO, with guidance on site constraints, approvals, structural connections, budgets, and construction.',
    intro:'An Arvada home addition can give you room for a changing household without giving up a familiar neighborhood. Start by comparing the space you need with the structure, site, and approvals that shape what can be built.',
    sections:[['Compare an expansion with a new layout','Before deciding how many square feet to add, ask whether reworking existing rooms could solve part of the problem. A kitchen expansion, a larger primary suite, and a second-story addition each connect to the home differently. Compare their structural implications, access, and effect on outdoor space.'],['Bring Arvada’s review requirements into early design','Confirm the property’s jurisdiction and zoning, then ask which plans and approvals the addition requires. For a property subject to historic or private design review, identify those steps early. A larger yard does not cancel setbacks, easements, or drainage constraints.'],['Allow for the old-to-new connection','Budget for foundation design, roof connections, utility capacity, and transitions into adjoining rooms. If the site raises geotechnical questions, resolve them with qualified professionals. The estimate should identify design, permits, construction, and any separately handled provider charges.']]},
  {service:'kitchen',city:'arvada',path:'/kitchen-remodeling-kitchen-renovations-arvada-co/',
    description:'Plan an Arvada kitchen remodel that coordinates layout, cabinets, utilities, storage, finishes, permits, and construction.',
    intro:'A better Arvada kitchen begins with how the room works. Summit coordinates kitchen renovations that bring the layout, utilities, storage, and finishes into one practical plan.',
    sections:[['Know whether the project is interior-only','Use Arvada’s residential interior-remodel guidance to discuss the work involved. Moving a wall, opening the room to an addition, or changing an exterior window can take the project beyond a finish update. Describe the full scope before selecting a permit path.'],['Review the kitchen’s existing systems','Assess the electrical service for new appliances, the exhaust route, and the plumbing layout. A home’s age can suggest questions, but the actual condition and prior work should inform the scope. Establish whether suspect materials need assessment before demolition.'],['Make cabinet and appliance decisions together','Measure clearances and confirm appliance specifications before orders. Decide how storage, lighting, and circulation will work with several people in the room. If exterior changes need city or private design approval, resolve them before finalizing the affected components.']]},
  {service:'kitchen',city:'golden',path:'/kitchen-remodeling-golden-co/',
    description:'Plan a Golden, CO kitchen remodel that connects storage and finishes with utilities, construction, permits, and historic-property needs.',
    intro:'Improve the everyday use of your Golden kitchen while respecting the home around it. A clear plan connects new storage and finishes with the systems and approvals the work may need.',
    sections:[['Verify the authority for the address','Check whether the property is in Golden or unincorporated Jefferson County. The correct building office should review the proposed structural, electrical, plumbing, and mechanical scope. Do not select an application based only on the postal city.'],['Consider the exterior before moving appliances','A new cooking location can require a different exhaust route; a new layout may suggest a changed window. If the property has a historic designation or lies within a protected district, discuss those exterior changes with Golden Planning before they become fixed design decisions.'],['Keep construction and selections aligned','Confirm cabinet dimensions, appliance specifications, utility needs, and surface choices as one coordinated package. Ask how existing floors and adjoining rooms will be protected and how the household will handle meals while the kitchen is unavailable.']]},
  {service:'kitchen',city:'lakewood',path:'/kitchen-renovations-kitchen-remodeling-lakewood-co/',
    description:'Plan a Lakewood kitchen remodel with a practical layout and coordinated plumbing, electrical, ventilation, finishes, and construction.',
    intro:'Create a Lakewood kitchen that fits the way you cook and gather. Summit helps connect a useful layout with the plumbing, electrical, ventilation, and construction work behind it.',
    sections:[['Separate a finish update from a layout change','A project that retains fixture locations differs from one that moves the sink, opens a wall, or expands the room. Identify those decisions first. They affect the information needed for permitting as well as the sequence of construction.'],['Check utility responsibilities when the scope changes','If the renovation changes a service or raises capacity questions, identify the water and wastewater providers for the address. Ask whether provider review is needed in addition to the building permits. The city is not automatically responsible for every utility serving the home.'],['Make room for real daily use','Work through appliance openings, preparation space, storage, and passage between rooms. In a split-level or previously altered home, check how changes affect nearby circulation and utility routes. Include floor transitions and adjoining finishes when comparing estimates.']]},
  {service:'bathroom',city:'denver',path:'/bathroom-renovations-denver-co/',
    description:'Plan a Denver bathroom remodel with coordinated layout, waterproofing, ventilation, fixtures, finishes, permits, and construction.',
    intro:'A Denver bathroom renovation should be comfortable to use and carefully built beneath the surface. Summit brings layout, waterproofing, ventilation, and finish decisions into a coordinated project.',
    sections:[['Describe all the work before choosing a permit path','Moving plumbing, changing wiring, or altering structure can require a different review from cosmetic work. Denver’s current residential and trade-permit resources are the starting point. Confirm the applications and inspection sequence for the complete bathroom scope.'],['Look at ventilation and windows in context','An interior renovation can include an exterior change when a fan needs a new outlet or a window moves. On a designated historic property, ask whether that detail needs preservation review. Resolve it before committing to the layout.'],['Protect the rest of the home','Discuss assessment of suspect materials, dust separation, debris routes, and access to another bathroom. Plan rough work and inspections before finishes conceal them. A shower conversion should include a complete drainage and waterproofing approach, not only a new tile selection.']]},
  {service:'bathroom',city:'golden',path:'/bathroom-remodeling-bathroom-renovations-golden-co/',
    description:'Plan a Golden, CO bathroom remodel for better comfort, daily function, shower access, storage, and carefully coordinated construction.',
    intro:'Make your Golden bathroom more usable with a renovation planned for the house it belongs to. Summit coordinates complete bathroom updates, shower changes, and improvements for easier access.',
    sections:[['Start with the location and existing room','Confirm whether Golden or Jefferson County governs the property. Then assess the bathroom’s dimensions, plumbing routes, floor assembly, and ventilation. Existing finishes do not tell the whole story of what is behind the walls.'],['Resolve exterior details on historic properties','If the project changes a window or adds an exhaust outlet, check the property’s historic status and ask Golden Planning about review. Age alone does not determine the requirement. Include approved exterior details in the construction documents.'],['Plan a shower around the floor','A low-threshold or curbless shower must fit the drainage and floor design. Consider seating, controls, lighting, and support locations before finish selections. Identify who will confirm the assembly and which inspections or tests belong in the sequence.']]},
  {service:'bathroom',city:'lakewood',path:'/bathroom-remodeling-bathroom-renovations-lakewood-co/',
    description:'Plan a Lakewood bathroom remodel with better storage, comfort, access, waterproofing, and coordinated construction behind the finished room.',
    intro:'Improve storage, comfort, and daily function in your Lakewood bathroom. Summit plans bathroom renovations with attention to the systems, construction details, and household needs around the room.',
    sections:[['Establish the existing conditions','A new vanity or shower layout may connect to plumbing below the floor and electrical work in adjacent walls. Review those routes before treating fixture relocation as a small change. For suspect materials, establish the assessment plan before demolition.'],['Clarify city and utility-provider responsibilities','Identify the governing building department and confirm the applicable permits. When adding a bathroom or changing utility capacity, ask the actual water and wastewater providers whether their review is needed. Provider requirements should be resolved before the estimate is treated as complete.'],['Make access part of the layout','Consider clear passage, door swings, storage, and the people using the room. A shower seat or future grab-bar location is easier to coordinate before walls are finished. Establish a usable alternative bathroom and protection for adjoining living space during construction.']]},
  {service:'bathroom',city:'morrison',path:'/bathroom-remodeling-bathroom-renovations-morrison-co/',
    description:'Plan a Morrison, CO bathroom remodel around daily function, access, waterproofing, utilities, permits, and property conditions.',
    intro:'A Morrison-area bathroom renovation begins with the room—and the property it serves. Summit coordinates bathroom improvements for comfort, daily function, and changing access needs.',
    sections:[['Confirm town or county jurisdiction','A Morrison postal address may be inside the town or in unincorporated Jefferson County. Check municipal status and use the appropriate building resources. A bathroom renovation stays connected to the property’s actual permits and utility arrangements.'],['Check wastewater before adding capacity','Determine whether the home uses a sanitation district or an on-site wastewater system. For a new bathroom or expanded household use, ask the responsible authority what evaluation is needed. Do not assume that space for another fixture establishes system capacity.'],['Distinguish interior work from an addition','An interior-only bathroom renovation is different from adding new exterior space. Jefferson County’s WUI guidance exempts interior-only alterations, while a covered addition or exterior change may involve other requirements. Define the scope accurately before applying a wildfire checklist.'],['Plan around access and daily use','Consider delivery access and staging, where debris will travel, and how the household will use another bathroom. Establish the drainage, ventilation, and waterproofing approach before ordering the finishes.']]},
  {service:'bathroom',city:'wheat-ridge',path:'/bathroom-renovations-bathroom-remodeling-wheat-ridge-co/',
    title:'Wheat Ridge Bathroom Remodeling | Summit Custom Builders',
    description:'Plan a Wheat Ridge bathroom remodel with coordinated layouts, showers, storage, waterproofing, utilities, and construction.',
    intro:'Bring better function to a Wheat Ridge bathroom without overlooking what supports it. Summit coordinates bathroom layouts, shower renovations, storage, and the work behind the finishes.',
    sections:[['Assess the existing bathroom before replacing it','Document what works and what does not: storage, lighting, door clearance, access, and ventilation. In an older room, ask about the condition of plumbing and the floor assembly. Previous renovations may matter as much as the original construction date.'],['Use the Building Division’s current process','Confirm which permits and inspections the work needs using Wheat Ridge’s current resources. Discuss layout revisions with the project team before rough work is covered. If added fixtures raise utility-capacity questions, contact the water and sanitation providers for the address.'],['Plan a conversion as a complete assembly','A tub-to-shower conversion involves dimensions, drainage, waterproofing, and the supporting floor. Consider future support locations and usable controls. Include assessment of suspect materials and a plan for household access in the construction sequence.']]}
];
