import { site } from '../config.mjs';
const guide=(id,slug,title,service,intro,sections,checklist,sources=[])=>({id,path:`/blog/${slug}/`,title,description:intro,intro,service,sections,checklist,sources,type:'guide',date:site.date,author:'Summit Custom Builders'});
export const guides=[
  guide('planning-addition','planning-home-addition-denver-metro','Planning a Home Addition in Denver Metro: Where to Start','additions',
    'Turn the need for more space into a useful project brief. Start with the household, the property, and the decisions that make an addition feasible.',[
      ['Write the problem before drawing the solution','Describe what you cannot do comfortably in the current house. You might need a main-floor bedroom, space for relatives, or a kitchen where two people can cook. List the activities and storage needs rather than starting with a square-foot target. This gives the design team room to compare a new addition with a better use of existing rooms.'],
      ['Gather the property information','Collect the address, any survey, prior plans, and records of earlier work. Confirm the permitting jurisdiction. For a Jefferson County address, municipal status can differ from the postal city. Ask about the parcel’s setbacks, easements, height limits, and any historic or private design review before treating a layout as buildable.'],
      ['Investigate the connections','The new room must work with foundations, structure, roof drainage, utilities, and the existing floor plan. A second story adds stair and load-path questions. A ground-floor expansion affects the yard and excavation. Discuss whether engineering, geotechnical review, environmental assessment, or utility-provider input is needed before design advances.'],
      ['Build a budget around the full project','Keep design and professional services, permits, construction, material allowances, temporary living costs, and contingency visible. Ask what is excluded and which costs depend on findings. A preliminary budget helps compare options; it should not be treated as a fixed construction price before the scope and conditions are established.'],
      ['Agree on the next decision','The first useful result may be a feasibility review or a measured concept, not a finished set of plans. Identify what information is missing, who obtains it, and what decision it will support. Set selection deadlines alongside the schedule so delayed appliances, windows, or finishes do not hold up later work.']
    ],['Project address and any existing plans','Must-have spaces and daily-use goals','Initial budget and timing constraints','Questions about occupancy during construction'],['address','denver']),
  guide('addition-cost','home-addition-cost-factors','Home Addition Costs: What Determines Your Budget?','additions',
    'An addition’s price depends on more than floor area. Understand the site work, structural connections, utilities, and choices that belong in a complete budget.',[
      ['Compare equivalent scopes','A bedroom addition and a kitchen expansion of the same size do not involve the same work. Bathrooms and kitchens bring fixtures, water, drainage, ventilation, and cabinetry into the project. Before comparing totals, establish what each estimate includes and whether the drawings, specifications, and allowances are equivalent.'],
      ['Separate site costs from room finishes','Access for equipment, excavation, soil conditions, foundation design, drainage, and the connection to the existing roof can materially affect the work. A constrained site may need a different construction approach. The finish list cannot answer those questions, so make feasibility and professional assessment part of budgeting.'],
      ['Understand allowances and exclusions','An allowance is a placeholder for an item that has not been fully selected. Ask what quantity and quality level it assumes, whether installation is included, and how an overage is handled. Identify design fees, permit fees, utility charges, landscaping restoration, and temporary accommodation that may sit outside the contractor’s price.'],
      ['Budget for discoveries without disguising scope','A contingency addresses uncertainty, such as concealed conditions found after opening the existing home. It should be separate from optional upgrades you already want. Discuss which investigations can reduce uncertainty before construction and how any change will be documented, priced, and approved.'],
      ['Ask for a decision-ready comparison','Request options that show what changes when scope changes: a smaller footprint, retained plumbing locations, or a simpler roof connection. Cutting an essential structural or water-management detail is different from choosing a less expensive finish. The practical goal is a complete, buildable scope that matches what you can spend.']
    ],['Same scope in each estimate','Named allowances and exclusions','Utility and professional-service costs','A separate contingency and written change process']),
  guide('addition-timeline','home-addition-timeline','How Long Does a Home Addition Take?','additions',
    'A realistic addition schedule separates planning, approvals, ordering, and construction. Learn which decisions and dependencies shape the sequence.',[
      ['Planning comes before the construction calendar','Feasibility, measurements, design, and engineering establish what will be built. The duration depends on the project and how quickly key decisions can be made. A useful schedule shows these stages separately instead of counting only the period with a crew on site.'],
      ['Confirm the actual approval sequence','The governing jurisdiction determines the applications and reviews. Historic review, zoning, utility coordination, and building permits may create separate steps. Ask which tasks can run together and which depend on an earlier approval. Use the authority’s current information; do not treat another project’s permit duration as a promise.'],
      ['Order against approved decisions','Windows, doors, cabinets, specialty fixtures, and other selected materials can affect the sequence. Finalize dimensions and specifications before ordering. Discuss the consequences of changing a selection after design or procurement. Confirm delivery readiness before demolition or disconnection makes the existing home harder to occupy.'],
      ['Understand the construction dependencies','Site preparation and foundations lead into framing and the weather enclosure. Rough plumbing, electrical, and mechanical work need coordination before insulation and finishes. Inspections, product installation requirements, and final connections are part of the schedule. Work that is hidden too soon can create rework.'],
      ['Make room for change without guessing dates','Weather, concealed conditions, inspection corrections, and delayed decisions can move completion. Ask for an updated schedule when a material change occurs. Agree on what “complete” means: final inspections, a walkthrough, remaining items, and the handoff of relevant documents.']
    ],['Planning and construction shown separately','Review steps for the exact address','Material-selection and order deadlines','Utility interruptions and move-out periods'],['denver','arvadaPermits']),
  guide('build-up-out','building-up-vs-building-out','Building Up vs. Building Out: Comparing Addition Options','additions',
    'A second story and a ground-floor expansion solve different problems. Compare structure, stairs, site use, and disruption before choosing a direction.',[
      ['Start with the daily-use goal','A main-floor bedroom may favor expansion at ground level; a growing household may benefit from additional upstairs bedrooms. Think about how occupants will move between rooms and whether stairs support the long-term plan. More floor area does not automatically create a more usable home.'],
      ['Building out: the site becomes part of the design','A ground-floor addition uses yard space and needs a foundation, roof connection, and drainage plan. Setbacks, easements, utility routes, and construction access can limit the footprint. The new floor must connect sensibly with the old one. Ask how the addition changes outdoor circulation and roof runoff.'],
      ['Building up: investigate the entire load path','A second story adds loads to the home below. An engineer needs to assess the structure and foundation; the existing roof is not evidence of spare capacity. Stair location, headroom, heating and cooling, and roof removal also shape the project. Height and design standards need review with the permitting authority.'],
      ['Compare disruption as well as construction','Both approaches can affect occupied rooms. Building up may require more extensive opening of the existing home, while building out can disrupt the yard and access. Establish whether temporary relocation is necessary and which utilities or rooms will be unavailable. Include those arrangements in the comparison.'],
      ['Choose from feasible options','Avoid deciding that one approach is always cheaper. Compare actual concepts after initial site and structural assessment. A smaller addition combined with interior changes may be another option. The strongest choice solves the household’s problem within the property’s constraints and the full project budget.']
    ],['Long-term stair and access needs','Structural feasibility','Zoning and available building envelope','Impact on yard, roof, and occupied rooms']),
  guide('addition-vs-moving','home-addition-vs-moving','Adding Onto Your Home vs. Moving: Questions to Consider','additions',
    'Compare what an addition can solve with what a different home would change. Include the full costs, the disruption, and what you value about staying.',[
      ['List what you would keep and what you need to change','Separate location-related benefits from house-related problems. A familiar neighborhood, nearby support, or a useful commute may be reasons to stay. A layout problem may be fixable. A site that cannot support the needed space may point in another direction. Start with priorities rather than a blanket assumption that either option is better.'],
      ['Check whether the addition is feasible','Before comparing a renovation budget with purchase prices, establish whether the desired project can be built. Zoning, site conditions, utilities, and the existing structure influence feasibility. If a proposal depends on a second story or a separate living unit, resolve the appropriate design and approval questions early.'],
      ['Compare complete costs','For an addition, include design, approvals, construction, temporary accommodation, financing costs where applicable, and contingency. For a move, include transaction expenses, moving costs, and changes the next home would need. Use current, property-specific numbers from the appropriate professionals; this guide does not estimate financial returns.'],
      ['Compare the experience','Construction brings decisions and disruption. Moving brings packing, a transition, and learning a different home. Consider household routines, work, school, pets, and caregiving. If accessibility is a priority, evaluate the whole route through each option rather than only the new room.'],
      ['Make the next step proportionate','A feasibility conversation and initial budget can provide enough information to compare paths before commissioning a full design. Ask which unresolved issue could change the decision most. Resolve that issue first, then refine the option that best supports your household.']
    ],['What matters about the current location','Feasibility of the space you need','Complete costs for both options','Disruption and long-term access needs']),
  guide('whole-home-plan','planning-whole-home-remodel','Planning a Whole-Home Remodel: Scope, Sequence, and Decisions','remodeling',
    'Organize a major renovation before individual room decisions pull it in different directions. Build a shared scope, sequence, and decision list.',[
      ['Write one brief for the whole home','List the rooms involved and the reason each needs work. Identify needs that cross room boundaries, such as storage, circulation, comfort, and accessibility. Agree on priorities with everyone who makes project decisions. A shared brief helps the designer and builder see connections that separate room wish lists can miss.'],
      ['Investigate systems and previous alterations','Gather existing plans, permit records, and information about past work. Assess structure, electrical capacity, plumbing, heating and cooling, and ventilation as the scope requires. Establish an environmental assessment plan before disturbing suspect materials. A previous renovation does not guarantee that the concealed work matches the new project’s needs.'],
      ['Decide what must happen together','Structural and utility changes can connect several rooms. Replacing finishes before resolving those changes may create avoidable rework. If the remodel will be phased, plan toward the final layout so early work supports later stages. Identify dependencies in drawings and in the estimate.'],
      ['Assign decisions and deadlines','Create a selection list for cabinets, appliances, fixtures, doors, flooring, and other specified materials. Establish who approves each decision and when it is needed. Identify who orders, receives, checks, and stores materials. A deadline is more useful when everyone understands which later task depends on it.'],
      ['Plan occupancy and communication','Agree on site access, working areas, temporary utilities, dust separation, and the rooms that remain available. Discuss updates, questions, and written changes. The project’s specific agreement should define responsibilities and completion rather than leaving them to assumptions.']
    ],['A whole-home priority list','Existing records and assessment needs','Linked work and phasing decisions','Selection ownership and deadlines']),
  guide('whole-home-cost','whole-home-remodeling-budget','Whole-Home Remodeling Costs: Building a Realistic Budget','remodeling',
    'Create a renovation budget that accounts for connected systems, finishes, temporary living arrangements, and uncertainty before work begins.',[
      ['Break the project into meaningful scopes','Organize the estimate around the work: demolition, structure, utilities, enclosure, interiors, and finishes. Room-by-room totals can be useful, but shared work must still be visible. Ask where costs for common systems, design, permits, protection, and cleanup are included so they are not missed or counted twice.'],
      ['Distinguish necessary work from chosen upgrades','A structural repair and a preferred finish serve different purposes. Make the essential construction scope clear before comparing aesthetic options. If a budget reduction is needed, ask which changes truly remove work and which merely postpone a connected task that will cost more to revisit.'],
      ['Treat allowances as decisions still to come','Document what each allowance covers, including quantity, material quality, delivery, and installation. Select representative products early enough to test whether the allowance fits your expectations. Do not rely on the lowest placeholder price when comparing estimates for a project you intend to finish differently.'],
      ['Account for life during the remodel','Include temporary housing, storage, meal arrangements, moving belongings, and any work-from-home adjustments that the household will need. Those may not be contractor charges, but they are still project costs. A phased project can reduce some disruption while introducing repeated setup or longer overall duration.'],
      ['Keep contingency and changes transparent','Identify concealed conditions that remain uncertain and the assessments that may reduce that uncertainty. Agree on how a discovered issue is documented and priced. Keep contingency separate from new requests so you can tell whether the project is using its reserve for unknown conditions or expanding its scope.']
    ],['Scope organized beyond room names','Realistic finish allowances','Temporary household costs','Separate contingency and optional upgrades']),
  guide('living-through-remodel','living-at-home-during-remodel','Can You Live at Home During a Major Remodel?','remodeling',
    'Staying home is a practical planning decision. Assess access, essential rooms, construction separation, and the stages when temporary relocation may be necessary.',[
      ['Start with essential daily functions','Identify where the household will sleep, bathe, prepare food, work, and store belongings. A room being physically untouched does not guarantee safe or practical access to it. Ask which utilities, routes, and exits will remain available during each construction stage.'],
      ['Discuss separation from the work area','Agree on construction routes, protection of occupied rooms, debris handling, and expectations about dust and noise. If specialist environmental work is needed, follow the qualified professional’s occupancy guidance. Do not assume plastic sheeting alone makes every stage suitable for occupancy.'],
      ['Plan for interruptions','Electrical, plumbing, heating, or cooling may need temporary shutdowns. A structural opening or roof change can affect enclosure and access. Ask how those events will be communicated and what arrangements need to be in place beforehand. A single overall finish date does not answer these day-to-day questions.'],
      ['Include everyone who lives there','Consider children, pets, mobility needs, caregiving, night-shift work, and people working from home. Noise and frequent access by trades can make a technically possible arrangement impractical. A short planned move-out period may be easier than repeatedly changing living arrangements during the work.'],
      ['Set a reassessment point','Concealed conditions or a scope change may alter the occupancy plan. Agree to reassess when significant changes occur. Keep access and safety decisions separate from pressure to remain in place simply because that was the original preference.']
    ],['Working bathroom and meal arrangements','Safe access and separation','Utility shutdown plan','Children, pets, and mobility considerations'])
];
guides.push(
  guide('kitchen-cost','kitchen-remodeling-cost-factors','Kitchen Remodeling Costs: Layout, Cabinets, and Construction','kitchen',
    'Understand what makes kitchen estimates differ. Compare the layout, cabinet package, installation work, and utility changes behind the total.',[
      ['Define the level of change','Retaining the room’s layout can avoid some relocation work, but it does not eliminate the need to assess existing systems. Moving a sink, opening a structural wall, or extending the kitchen into an addition changes the scope. Decide which improvements are essential before selecting a finish package.'],
      ['Price a coordinated cabinet and appliance plan','Cabinet construction, storage accessories, installation details, appliance dimensions, and surface fabrication need to work together. An appliance allowance that excludes electrical or ventilation changes may understate the project. Confirm what is included before comparing estimates with different levels of specification.'],
      ['Look behind the visible finishes','Electrical capacity, lighting, ventilation, plumbing routes, substrate preparation, and structural work are part of a usable kitchen. Identify which existing conditions have been assessed and which remain uncertain. Ask whether environmental assessment or specialist work is needed before removing suspect finishes.'],
      ['Clarify purchasing responsibility','If you supply materials, agree on who checks specifications, arranges delivery, stores items, and handles damaged or incompatible products. A purchase price alone does not cover installation and coordination. Establish what happens if a late or changed selection affects the schedule.'],
      ['Keep the household costs visible','Budget for meal arrangements and the period without a full kitchen. Consider whether adjoining flooring, paint, or trim must change for a complete result. Compare options by the work they actually remove, and preserve the details needed for a sound installation.']
    ],['Layout and appliance decisions','Complete cabinet and installation scope','Utility work and adjoining finishes','Purchasing and temporary-meal responsibilities']),
  guide('bathroom-cost','bathroom-remodeling-cost-factors','Bathroom Remodeling Costs: What Changes the Price?','bathroom',
    'The size of a bathroom is only one cost factor. Consider fixture locations, preparation, waterproofing, tile work, and the conditions behind existing finishes.',[
      ['Compare the actual scope','A surface refresh, a full replacement in the existing layout, and a relocated bathroom involve different work. Moving a toilet or shower can affect framing and plumbing beyond the room itself. Establish which fixtures stay and which move before comparing material prices.'],
      ['Include the complete shower assembly','The finished tile is one part of the shower. Substrate, waterproofing, drainage, transitions, and compatible installation details all matter. Custom glass, benches, niches, and a curbless entry can change the construction requirements. Ask for those choices to be reflected in the scope rather than added after rough work.'],
      ['Identify labor-intensive finish decisions','Large or small tile, complex patterns, numerous corners, and custom fabrication can change installation work. Vanity choices and fixture specifications also affect preparation. Compare complete installed scopes, not just a price per box of tile or a showroom fixture price.'],
      ['Plan for concealed conditions','Existing moisture damage, an unsuitable floor assembly, or outdated utility work may change the project after surfaces are opened. Establish which assessments can happen beforehand, including any necessary review of suspect materials. Keep contingency separate from optional upgrades.'],
      ['Include access and household arrangements','Protecting adjacent rooms, removing debris, coordinating inspections, and maintaining bathroom access require planning. A home with only one bathroom may need temporary arrangements outside the contractor’s estimate. Request a complete list of inclusions, exclusions, and selection responsibilities.']
    ],['Fixture locations and floor assembly','Waterproofing and drainage scope','Installed finish costs','Alternative bathroom and contingency']),
  guide('hiring-contractor','questions-before-hiring-general-contractor','Questions to Ask Before Hiring a General Contractor','contractor',
    'Use specific questions to compare builders: relevant experience, credentials for your address, scope, changes, communication, and completion.',[
      ['Who is responsible for the work at my address?','Ask which business will sign the agreement and which person will coordinate construction. Confirm the governing city or county and the credentials required there. Request current insurance information and verify applicable trade licenses with the issuing authority. A general marketing statement about being licensed does not answer every jurisdiction or scope question.'],
      ['Can I speak with clients from similar projects?','Ask about work comparable in scope and complexity, not only attractive finished photographs. A kitchen refresh and a structural addition involve different coordination. With the clients’ permission, ask about communication, changes, site protection, and how remaining items were handled after the main work.'],
      ['What exactly does the estimate include?','Review drawings, specifications, allowances, exclusions, permit responsibility, material purchasing, and site arrangements. Ask how the estimate addresses conditions that cannot be fully seen. Compare the same scope across proposals so a missing item does not appear to be a saving.'],
      ['How will changes and updates be handled?','Find out who answers questions and how decisions are recorded. Ask for the cost and schedule effect of a proposed change before it proceeds. Establish a communication method and cadence in the agreement rather than assuming that daily contact or immediate responses are included.'],
      ['What does completion mean?','Discuss inspection closeout, the final walkthrough, remaining work, product information, and warranty documents. Confirm how payment milestones relate to the agreement. Keep copies of the contract, written changes, selections, and relevant approvals so the project has a shared record.']
    ],['Business identity, local credentials, and insurance','References for comparable work','Equivalent scope and clear exclusions','Written changes and defined completion'],['arvadaPermits','denver']),
  guide('aging-checklist','aging-in-place-remodeling-checklist','Aging-in-Place Remodeling Checklist for Your Home','aging',
    'Use everyday tasks to identify practical home improvements. Review entry, circulation, bathing, cooking, lighting, and the possibility of same-floor living.',[
      ['Follow the route into the home','Start where someone parks or is dropped off. Consider steps, thresholds, weather exposure, lighting, and opening the door while carrying items or using mobility equipment. Measure the actual route and discuss the person’s needs. A ramp or widened door is only useful if it connects to a workable path inside.'],
      ['Review bathing and toileting','Discuss shower access, seating, controls, support locations, floor transitions, and lighting. A professional can help identify functional requirements for an individual user. Construction planning should establish backing, drainage, and the floor assembly before finishes. Do not rely on a product’s “accessible” label as proof that the whole room will work.'],
      ['Look at kitchen reach and movement','Review frequently used items and how they are reached. Consider storage, hardware, appliance doors, task lighting, and space to prepare food seated if needed. Check how two people, or a person and a caregiver, would use the room together.'],
      ['Consider same-floor routines','Locate sleeping, bathing, meals, and essential daily activities on a plan. Moving one task downstairs may not solve a route that still requires repeated stair use. Compare reconfiguring existing space with an addition and discuss the disruption each option would create.'],
      ['Prioritize with the right people','Separate immediate needs from future preparation. Involve the occupant, household, and appropriate healthcare or accessibility professionals. Private-home access needs are not identical to public-facility ADA requirements. Confirm the applicable rules for the property’s use and avoid treating a checklist as certification of compliance.']
    ],['Entry and continuous usable routes','Bathroom support and access','Kitchen reach and lighting','Immediate needs and future preparation'],['ada']),
  guide('asbestos','colorado-asbestos-before-remodeling','Asbestos Before a Colorado Remodel: What to Clarify','remodeling',
    'Resolve suspect-material questions before demolition. Inspection, abatement, and notification are different steps, and the project’s details determine what applies.',[
      ['Do not use the home’s age as the whole answer','Asbestos rules do not reduce to a simple “old house” test. Colorado’s Regulation 8 describes inspection requirements and a documented exemption for qualifying later construction; a construction date alone does not establish the exemption. A certified asbestos building inspector can help define the affected materials and the appropriate inspection scope.'],
      ['Separate assessment from abatement','The regulation distinguishes suspect material, confirmed or assumed asbestos-containing material, its condition, quantity, and how work will disturb it. Exceeding a surface-area figure does not automatically mean every finish must be professionally removed. Ask the certified professional to explain the findings and requirements for the actual project.'],
      ['Make the report useful to the construction team','Provide a clear description of the planned demolition and affected rooms. If the scope later expands, ask whether the original assessment still covers it. Keep the findings available to the people coordinating the work so a new opening or added room does not proceed on an outdated assumption.'],
      ['Allow for the required sequence','Where regulated abatement or demolition notification is required, it can affect the start date. Confirm the applicable notice period, specialist availability, and any required clearance with CDPHE and the qualified contractor before scheduling downstream work. Do not turn a notification period into a promise about the total project duration.'],
      ['Ask four questions before work begins','Who is qualified to assess the materials? Which areas and layers will the inspection cover? What happens if the layout or demolition scope changes? What documents and conditions must be satisfied before general construction resumes? These questions are more useful than trying to identify materials by appearance or taking samples yourself.']
    ],['Defined demolition scope','Certified assessment where required','Documented findings and next steps','Confirmed notification and clearance sequence'],['asbestosRule','asbestos']),
  guide('soils','expansive-soils-dipping-bedrock-home-additions','Expansive Soils and Dipping Bedrock: Planning a Home Addition','additions',
    'A foundation plan starts with the ground. Understand why mapped hazards, site investigation, drainage, and the old-to-new connection belong in addition planning.',[
      ['Use maps to raise the right questions','Jefferson County identifies geologic constraints including dipping bedrock, subsidence, and slope hazards. Mapping helps screen a property for further investigation; it does not replace a site-specific assessment. Do not conclude that every home in a named neighborhood shares the same ground conditions.'],
      ['Understand the dipping-bedrock distinction','The county’s Designated Dipping Bedrock Area identifies a potential heaving-bedrock hazard. Its guidance explains that steeply inclined expansive layers can respond unevenly to water. That behavior can complicate design and requires appropriate geological and geotechnical attention. A nearby building performing well is not a substitute for evaluating the proposed addition.'],
      ['Connect the new foundation to the existing home','An addition places new construction beside an older structure. Ask the design professionals to assess the existing foundation, the proposed loads, and how the two parts connect. The appropriate foundation system comes from the site and engineering findings, not a standard detail chosen from a similar-looking project.'],
      ['Treat drainage as part of the building work','An addition changes roof runoff and can alter ground surfaces, paths, or irrigation. Discuss how water will be managed during excavation and after completion. The geotechnical and civil recommendations should inform the construction scope. Avoid making late landscaping changes that conflict with the site’s drainage plan.'],
      ['Keep the findings through completion','Identify which reports and design recommendations the construction team needs, which observations are required during work, and which maintenance guidance belongs in the handoff. Budget for investigation early enough that it can change the design before major commitments.']
    ],['Parcel-specific hazard screening','Geotechnical and structural questions','Construction and permanent drainage','Reports, observations, and maintenance guidance'],['geology','ddba']),
  guide('radon','radon-and-home-remodeling','Radon and Your Remodel: Questions to Ask Before Walls Close','remodeling',
    'Include indoor-air questions in renovation planning. Testing and professional assessment can inform decisions while routes and building systems remain accessible.',[
      ['Start with an actual test','EPA recommends testing homes for radon. A neighbor’s result, a home’s appearance, or a regional risk map cannot tell you the result in your own home. Keep any prior test records and follow the current instructions for the test method being used.'],
      ['Tell the professional what will change','Share the renovation plans with the person assessing radon. Explain any changes to occupied space, foundations, heating and cooling, or the building enclosure. This gives the professional context for advising on testing and any mitigation needs; a remodel does not by itself establish that a radon problem exists.'],
      ['Coordinate routes before finishes','If mitigation is needed, discuss routing and equipment locations before new walls or ceilings close. Coordinate with the project’s mechanical, electrical, and other work so one system does not obstruct another. The qualified radon professional should determine the approach rather than having the remodeling crew improvise it.'],
      ['Protect an existing system','Identify existing mitigation equipment and components on the plans. Discuss any proposed relocation or changes with the appropriate professional. Ask which checks or follow-up testing are needed after the renovation, and keep the instructions and records with the home’s other project documents.'],
      ['Keep the responsibilities clear','Summit’s role is to coordinate construction. Testing, interpretation, and mitigation should be assigned to appropriately qualified professionals. Include those services in the scope or list them as owner-arranged items so they do not disappear between the design and construction stages.']
    ],['Prior results and a current testing plan','Planned system and enclosure changes','Mitigation coordination if needed','Post-work checks and records'],['radon']),
  guide('older-homes','older-home-systems-before-remodeling','What to Check Behind the Walls of an Older Home','remodeling',
    'Use the home’s history to guide investigation, not to predict defects. Review structure, utilities, materials, and earlier alterations before major work.',[
      ['Start with records and visible evidence','Gather the construction date, plans, previous permits, and any available inspection or repair records. A house may contain original rooms alongside additions from several decades. Make a list of what is known and what needs investigation rather than assigning the whole home a condition based on its age.'],
      ['Ask structural questions before opening the layout','Walls, beams, posts, foundations, and earlier changes work together. A designer or structural engineer can establish what supports what and which proposed openings require a new design. Do not assume that a wall is nonstructural because it is thin or because a neighbor removed a similar one.'],
      ['Check the systems serving the proposed rooms','Review electrical capacity and circuits for the new appliances, plumbing routes and condition, ventilation, and heating or cooling needs. An older system may be usable, require repair, or need updating for the new scope. Have the relevant qualified trades assess it rather than promising a blanket replacement.'],
      ['Plan for suspect materials before disturbance','For pre-1978 housing, ask about lead-safe renovation requirements when painted surfaces will be disturbed. Asbestos assessment involves separate rules and qualifications. Establish the scope of any specialist assessment before demolition, and revisit it if the project expands. Avoid sampling or disturbing suspect materials simply to investigate on your own.'],
      ['Translate findings into decisions','Ask which findings change design, which change cost, and which affect the order of work. Keep allowances and contingency visible. A written record of what remains unknown helps the household and builder respond to discoveries without confusing necessary work with a new design request.']
    ],['Prior plans, permits, and alterations','Structure and utility assessments','Lead and asbestos questions','A record of findings and remaining uncertainty'],['lead','asbestosRule']),
  guide('jeffco','jefferson-county-remodeling-property-checks','Jefferson County Property Checks Before a Remodel or Addition','additions',
    'A mailing address is only the beginning. Confirm municipal status, mapped constraints, utility providers, and the review path for the actual property.',[
      ['Check municipal status first','Jefferson County’s address lookup can identify whether a property is inside a municipality or in an unincorporated area. Use that information to contact the right building and planning offices. A Golden or Morrison mailing address does not automatically establish that the named city or town issues the permits.'],
      ['Review mapped site constraints','Use the county’s geology resources to identify dipping bedrock, subsidence, or slope questions, and ask the authority about other applicable overlays. Maps guide the next investigation. They do not establish a specific foundation design or prove a parcel is free of hazards.'],
      ['Check wildfire scope as well as the map','The county’s wildfire resiliency guidance, effective July 1, 2026, applies to covered work in its unincorporated WUI. Interior-only alterations are exempt. Class 1 and Class 2 areas differ, and exterior projects have scope-specific provisions. Use the current county guidance for the actual proposal rather than applying every requirement to every remodel.'],
      ['Identify infrastructure beyond the building department','Determine who supplies water and handles wastewater. If the property uses a well or on-site wastewater system, contact the responsible authority before assuming it can serve additional rooms or fixtures. Clarify any separate approvals, assessments, and charges. Keep those responsibilities visible in the project budget.'],
      ['Turn the checks into an early project brief','Record the jurisdiction, provider contacts, applicable mapped conditions, and questions requiring professional review. Share that brief with the design and construction team. This helps the proposed floor plan respond to property information while changes are still straightforward.']
    ],['Municipal status and permitting authority','Mapped hazards and professional assessment','WUI classification and actual work scope','Water, wastewater, and access questions'],['address','geology','wildfire'])
);

// Refresh matching articles at their established URLs instead of creating duplicates.
const refresh = {
  'hiring-contractor': ['/construction-company-in-arvada-lakewood-co-denver-wheat-ridge-and-nearby-cities/','2022-05-27'],
  'addition-vs-moving': ['/home-addition-in-golden-co-denver-lakewood-co-arvada-wheat-ridge-and-surrounding-areas/','2022-03-17'],
  'aging-checklist': ['/ada-remodeling-in-arvada-denver-golden-lakewood-morrison-and-wheat-ridge-co/','2021-01-10']
};
for (const g of guides) if (refresh[g.id]) { g.plannedPath=g.path; [g.path,g.originalDate]=refresh[g.id]; }
export const guideById=Object.fromEntries(guides.map(g=>[g.id,g]));
