// Substantive topics retained and edited at their original article URLs.
export const legacyArticles = [
  {id:'kitchen-routines',service:'kitchen',path:'/kitchen-remodeling-in-arvada-denver-golden-lakewood-morrison-and-wheat-ridge-co/',title:'Kitchen Remodel Planning: Design Around Your Routine',originalDate:'2021-02-20',intro:'A kitchen that looks right should also work for your routines. Use cooking, storage, and gathering habits to guide the renovation.',sections:[
    ['Follow a normal day','Write down how you use the room on a weekday and when guests visit. Notice where food lands after shopping, where ingredients are prepared, and where dishes wait. These observations help identify practical improvements that a showroom photograph cannot choose for you.'],
    ['Plan for the people cooking','A household with several cooks may need preparation space in more than one place. Another household may prefer a compact, efficient layout. Consider appliance doors, clear passage, and where guests gather so conversation does not block the work area.'],
    ['Keep what already works','A useful existing layout or sound cabinetry may be worth retaining. Identify the missing functions before assuming the room needs to be completely rebuilt. New hardware, lighting, or storage can be part of a larger discussion, while structural and utility changes require a different level of planning.'],
    ['Turn preferences into a coordinated scope','Share the priorities with the design and construction team. Confirm appliance dimensions, service requirements, storage details, and finish transitions before orders. The goal is a kitchen that supports your household rather than a collection of unrelated features.']
  ]},
  {id:'remodel-priorities',service:'remodeling',path:'/home-remodeling-in-arvada-denver-golden-lakewood-morrison-and-wheat-ridge-co/',title:'Which Rooms Should You Remodel First?',originalDate:'2021-02-10',intro:'Choose which rooms to remodel first by weighing daily function, connected systems, household priorities, budget, and long-term plans for your Denver-area home.',sections:[
    ['Identify the recurring frustration','Start with problems you encounter repeatedly: a crowded kitchen, insufficient storage, an inconvenient bathroom, or no quiet place to work. Describe the task that is difficult and who it affects. This is a stronger basis for setting priorities than following a trend.'],
    ['Look for connected work','A kitchen, bathroom, and nearby living area may share utility routes or finishes. If changes are likely in several rooms, consider them together before completing one in isolation. The best first phase may address underlying systems that support the later improvements.'],
    ['Consider comfort and privacy','Rooms serve different purposes. A kitchen may be a gathering place while a bedroom or bathroom needs privacy. Decide which improvements should help people come together and which should create a quieter retreat.'],
    ['Test the plan against the household','Compare the benefits with the construction disruption and available budget. Identify the essential changes, the optional ones, and work that can wait without causing rework. Use that list to start a focused conversation with your builder.']
  ]},
  {id:'bathroom-users',service:'bathroom',path:'/bathroom-remodeling-in-arvada-denver-golden-lakewood-morrison-and-wheat-ridge-co/',title:'Bathroom Remodel Planning: Design for Daily Use',originalDate:'2021-01-20',intro:'Plan a Denver-area bathroom remodel around the people using it, with practical guidance for layout, storage, access, fixtures, and long-term daily comfort.',sections:[
    ['Decide what the room needs to provide','A short visit, an overnight stay, and everyday household use place different demands on a bathroom. Identify whether the room needs bathing, extensive storage, space for several users, or easier access for a particular person.'],
    ['Prioritize function before adding features','More fixtures can make a small room harder to use. Work through door swings, clear passage, towel storage, lighting, and how the shower or tub is entered. Measure the available space rather than assuming that every desired feature fits.'],
    ['Coordinate a primary suite with the rest of the home','If you want a private bathroom while retaining a useful guest bathroom, assess both spaces together. Fixture placement, plumbing routes, and household access during construction can connect the projects.'],
    ['Think ahead about changing needs','Discuss support locations, reachable controls, and floor transitions while the room is being planned. Individual needs should inform the design. Appropriate backing and construction details matter as much as the finish selected for a safety feature.']
  ]},
  {id:'welcome',service:'contractor',path:'/welcome-to-summit-custom-builders/',title:'Building Communities by Building Relationships',originalDate:'2020-12-11',intro:'A remodel starts with people: the routines, memories, and expectations connected to a home.',noindex:true,sections:[
    ['Begin with the conversation','Summit Custom Builders’ approach puts listening at the beginning of a project. A room addition, kitchen renovation, bathroom remodel, or access improvement starts with understanding what the household wants to change and what it wants to keep.'],
    ['Connect the vision to the work','The details behind a finished space include structure, trades, materials, and coordination. Clear communication helps turn the initial picture of a project into decisions that can be designed, priced, and built.'],
    ['Tell us about your next chapter','Bring the address, the goals, and any information you already have. Summit serves Denver, Arvada, Wheat Ridge, Lakewood, Morrison, and Golden. The next conversation can help establish which details are needed to explore the project.']
  ]}
].map(p=>({...p,type:'guide',legacy:true,description:p.intro,date:'2026-09-20',author:'Summit Custom Builders',sources:[]}));
