import { execFileSync } from 'node:child_process';
import { readFile, writeFile, rename, mkdir, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { videoCatalog } from '../src/video-catalog.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const ffmpeg=process.env.FFMPEG||'ffmpeg',ffprobe=process.env.FFPROBE||'ffprobe';
const output=path.join(root,'public/assets');await mkdir(output,{recursive:true});
const assets={},report=[];
for(const [id,clip] of Object.entries(videoCatalog)) {
  const input=path.join(root,'website videos',clip.source);
  const originalBytes=(await stat(input)).size;
  const versions={};
  for(const height of [480,720]) {
    const temp=path.join(output,`motion-${id}-${height}.tmp.mp4`);
    execFileSync(ffmpeg,['-hide_banner','-loglevel','error','-i',input,'-map','0:v:0','-an','-sn','-dn','-vf',`scale=-2:${height}:flags=lanczos`,'-c:v','libx264','-preset','slow','-crf',height===480?'26':'25','-maxrate',height===480?'800k':'1400k','-bufsize',height===480?'1600k':'2800k','-pix_fmt','yuv420p','-profile:v','high','-level','3.1','-g','48','-threads','3','-map_metadata','-1','-movflags','+faststart','-y',temp],{stdio:['ignore','ignore','inherit']});
    const data=await readFile(temp),hash=createHash('sha256').update(data).digest('hex').slice(0,12);
    const file=`motion-${id}-${height}-${hash}.mp4`;await rename(temp,path.join(output,file));
    const media=JSON.parse(execFileSync(ffprobe,['-v','quiet','-show_streams','-show_format','-print_format','json',path.join(output,file)],{encoding:'utf8'}));
    const v=media.streams.find(s=>s.codec_type==='video');
    versions[height]={url:'/assets/'+file,bytes:data.length,width:v.width,height:v.height,duration:Number(media.format.duration)};
  }
  assets[id]=versions;report.push({id,source:'website videos/'+clip.source,originalBytes,versions});
  console.log(`${id}: 480p ${Math.round(versions[480].bytes/1024)} KB; 720p ${Math.round(versions[720].bytes/1024)} KB`);
}
await writeFile(path.join(root,'src/video-assets.mjs'),'// Generated by npm run videos. Prepared assets require no runtime encoder.\nexport const videoAssets = '+JSON.stringify(assets,null,2)+';\n');
await writeFile(path.join(root,'data/video-assets.json'),JSON.stringify(report,null,2));
console.log('Six films prepared. Original footage remains unchanged.');
