import { scrollHero } from './scroll-hero.mjs';
import { site, paths, source } from './config.mjs';
import { escapeHtml as e, jsonScript, link, sections, list, slug } from './html.mjs';
import { services, serviceById } from './content/services.mjs';
import { cities, cityById, localServices } from './content/cities.mjs';
import { guides, guideById } from './content/guides.mjs';
import { legacyArticles } from './content/legacy.mjs';
import { renderForm } from './form.mjs';
import { motionFigure } from './videos.mjs';
import { serviceVideo } from './video-catalog.mjs';
import { photos, servicePhotos, guidePhoto, photoUrl, picture, photoFigure, photoSections, detailPair, quietPhotos, galleryMarkup, projectDetailPhotos } from './photos.mjs';

export const nav=[['Services',paths.services],['Service areas',paths.areas],['Our projects',paths.projects],['Our process',paths.process],['About',paths.about],['Resources',paths.resources]];
const cta=(label='Request a consultation')=>link(paths.contact,label+' ↗','button');
export const sourceLinks = keys => keys?.length ? `<section class="sources"><h2>Official resources & further reading</h2><p class="small">Resources referenced September 11, 2026. Confirm the current requirements for your address and scope before applying.</p><ul>${[...new Set(keys)].map(k=>{if(!source[k])throw new Error('Unknown source '+k);return `<li>${link(source[k][1],source[k][0])}</li>`;}).join('')}</ul></section>` : '';
const card=(url,title,text,label='Explore',photoId=null)=>`<a class="content-card${photoId?' content-card--photo':''}" href="${e(url)}">${photoId?`<div class="card-photo">${picture(photoId,{sizes:'(max-width: 500px) calc(100vw - 42px), (max-width: 800px) 44vw, 400px',decorative:true})}</div>`:''}<div class="card-content"><div><h3>${e(title)}</h3><p>${e(text)}</p></div><span class="card-link">${e(label)} <span aria-hidden="true">↗</span></span></div></a>`;
const serviceCards=()=>`<div class="card-grid">${services.map(s=>card(s.path,s.name,s.summary,'View service',servicePhotos[s.id][0])).join('')}</div>`;
const cityCards=()=>`<div class="card-grid city-grid">${cities.map(c=>card(c.path,c.name,c.focus,'Local planning')).join('')}</div>`;
const guideCards=ids=>`<div class="card-grid">${ids.map(id=>{const g=guideById[id];if(!g)throw new Error('Unknown guide '+id);return card(g.path,g.title,g.intro,'Read guide',guidePhoto(g));}).join('')}</div>`;
const serviceShowcase=()=>`<section class="service-showcase" aria-label="Explore our remodeling services">${services.slice(0,2).map((s,i)=>`<article class="service-feature${i?' service-feature--reverse':''}"><a class="service-feature-photo" href="${s.path}" aria-label="Explore ${e(s.name)}">${picture(servicePhotos[s.id][0],{sizes:'(max-width: 800px) calc(100vw - 42px), 780px',decorative:true})}</a><div class="service-feature-copy"><p class="eyebrow">${i?'Rework the way you live':'Make room for what comes next'}</p><h2>${e(s.name)}</h2><p>${e(s.intro)}</p><ul>${s.options.slice(0,3).map(o=>`<li>${e(o)}</li>`).join('')}</ul>${link(s.path,'Explore '+s.name+' ↗','text-link')}</div></article>`).join('')}<div class="service-secondary-grid">${services.slice(2).map(s=>card(s.path,s.name,s.summary,'Explore service',servicePhotos[s.id][0])).join('')}</div></section>`;
const galleryPreview=()=>`<section class="gallery-preview-section" id="spaces-in-motion"><div class="section-heading split-heading"><div><p class="eyebrow">Spaces & construction</p><h2>A closer look at home.</h2></div><p>Finished rooms, the details within them, and new space taking shape. Explore the photos and short videos.</p></div>${galleryMarkup({curated:true})}${link(paths.projects,'Explore the full gallery ↗','text-link')}</section>`;
const breadcrumb=items=>`<nav class="breadcrumbs" aria-label="Breadcrumb"><ol>${[['Home','/'],...items].map(([label,path],i,a)=>`<li>${i===a.length-1?`<span aria-current="page">${e(label)}</span>`:link(path,label)}</li>`).join('')}</ol></nav>`;
const intro=(eyebrow,title,text)=>`<header class="page-intro"><p class="eyebrow">${e(eyebrow)}</p><h1>${e(title)}</h1><p class="lead">${e(text)}</p></header>`;
const faq=items=>`<section class="faq"><h2>Questions before you start</h2>${items.map(([q,a])=>`<details><summary>${e(q)}</summary><p>${e(a)}</p></details>`).join('')}</section>`;
const contactBand=()=>`<section class="contact-band"><div><p class="eyebrow">Your home. Your next chapter.</p><h2>Let’s talk about what’s possible.</h2><p>Bring your ideas, your questions, and the address. We’ll start there.</p></div><div>${cta()}${link('tel:'+site.tel,site.phone,'phone-link')}</div></section>`;
function sidebar(items,service=null) {
  return `<aside class="page-sidebar"><nav aria-label="On this page"><p class="eyebrow">On this page</p><ul>${items.map(([title])=>`<li>${link('#'+slug(title),title)}</li>`).join('')}</ul></nav><div class="sidebar-cta"><p class="eyebrow">Start a conversation</p><h2>A plan for your home.</h2><p>Tell us what you want to change.</p>${cta()}${service?link(service.path,'Explore '+service.name,'text-link'):''}</div></aside>`;
}
export function shell(page,body) {
  const hasScrollHero = body.includes('id="home-world"');
  const sectionMotion = ![paths.privacy, paths.accessibility, paths.thanks, paths.sitemap, '/404/'].includes(page.path);
  const noindex=page.noindex || process.env.PUBLIC_INDEXING!=='true';
  const canonical=site.url+page.path;
  const primaryPhoto=page.type==='guide'?guidePhoto(page):servicePhotos[page.service||page.id]?.[0]||'island';
  const shareImage=site.url+photoUrl(primaryPhoto);
  const business={'@type':'GeneralContractor','@id':site.url+'/#business',name:site.name,legalName:site.legalName,url:site.url,telephone:site.tel,address:{'@type':'PostalAddress',...site.address},logo:site.url+'/assets/logo.png',areaServed:cities.map(c=>({'@type':'City',name:c.name+', Colorado'}))};
  const graph=[business,{'@type':'WebSite','@id':site.url+'/#website',url:site.url,name:site.name,publisher:{'@id':business['@id']}},{'@type':'WebPage','@id':canonical+'#webpage',url:canonical,name:page.title,description:page.description,isPartOf:{'@id':site.url+'/#website'},about:{'@id':business['@id']},primaryImageOfPage:{'@type':'ImageObject',contentUrl:shareImage,width:1280,height:720}}];
  if(page.breadcrumbs) graph.push({'@type':'BreadcrumbList',itemListElement:[['Home','/'],...page.breadcrumbs].map(([name,path],i)=>({'@type':'ListItem',position:i+1,name,item:site.url+path}))});
  if(page.type==='guide') graph.push({'@type':'Article',image:[shareImage],headline:page.title,description:page.description,datePublished:page.originalDate||page.date,dateModified:page.date,author:{'@id':business['@id']},publisher:{'@id':business['@id']},mainEntityOfPage:{'@id':canonical+'#webpage'}});
  if(page.type==='service'||page.type==='local-service') graph.push({'@type':'Service',name:page.heading||page.title,provider:{'@id':business['@id']},areaServed:page.city ? {'@type':'City',name:cityById[page.city].name+', Colorado'} : business.areaServed,url:canonical});
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title>${e(page.title)}</title><meta name="description" content="${e(page.description)}"><meta name="robots" content="${noindex?'noindex, follow':'index, follow, max-image-preview:large'}"><link rel="canonical" href="${e(canonical)}"><meta name="theme-color" content="#81411c"><meta property="og:type" content="${page.type==='guide'?'article':'website'}"><meta property="og:site_name" content="${e(site.name)}"><meta property="og:title" content="${e(page.title)}"><meta property="og:description" content="${e(page.description)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${shareImage}"><meta property="og:image:width" content="1280"><meta property="og:image:height" content="720"><meta property="og:image:alt" content="${e(photos[primaryPhoto].alt)}"><meta name="twitter:card" content="summary_large_image">${process.env.GOOGLE_SITE_VERIFICATION?`<meta name="google-site-verification" content="${e(process.env.GOOGLE_SITE_VERIFICATION)}">`:''}<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css">${hasScrollHero?'<link rel="preload" as="image" href="/assets/scroll-hero/light-clean-poster.jpg" fetchpriority="high"><link rel="stylesheet" href="/assets/scroll-hero/hero.css"><script src="/assets/scroll-hero/scrub-engine.js" defer></script><script src="/assets/scroll-hero/hero.js" defer></script>':''}<script type="application/ld+json">${jsonScript({'@context':'https://schema.org','@graph':graph})}</script><script src="/assets/site.js" defer></script>${sectionMotion?'<link rel="stylesheet" href="/assets/section-scroll.css"><script src="/assets/gsap.min.js" defer></script><script src="/assets/scroll-trigger.min.js" defer></script><script src="/assets/split-text.min.js" defer></script><script src="/assets/section-scroll.js" defer></script>':''}${(body.includes('data-motion-player')||body.includes('data-film='))?'<script src="/assets/motion.js" type="module"></script>':''}</head>
    <body${hasScrollHero?' class="home-scroll"':''}><a class="skip-link" href="${hasScrollHero?'#home-content':'#main'}">${hasScrollHero?'Skip the visual tour':'Skip to content'}</a>${hasScrollHero?`<header class="home-navigation"><details class="home-menu"><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Main navigation">${nav.map(([label,path])=>link(path,label)).join('')}${link(paths.contact,'Request a consultation ↗')}</nav></details></header>`:`<div class="utility-bar"><div class="container"><span>Serving Denver & the surrounding communities</span>${link('tel:'+site.tel,site.phone)}</div></div>
    <header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Summit Custom Builders home"><img src="/assets/logo.png" width="169" height="43" alt="Summit Custom Builders"></a><details class="navigation" open><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Main navigation">${nav.map(([label,path])=>`<a href="${path}"${page.path===path?' aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-contact" href="${paths.contact}"${page.path===paths.contact?' aria-current="page"':''}>Contact <span aria-hidden="true">↗</span></a></nav></details></div></header>
`}
    <main id="main">${body}${[paths.privacy,paths.accessibility,paths.thanks,paths.sitemap,'/404/'].includes(page.path)?quietPhotos():''}</main>
    <footer class="site-footer"><div class="container footer-grid"><div><p class="footer-brand">Summit<br>Custom Builders<span>Communication. Construction. Completion.</span></p><p>Homes that fit every chapter of life.</p><address>${e(site.address.streetAddress)}<br>Denver, CO 80219<br>${link('tel:'+site.tel,site.phone)}</address></div><div><h2>What we build</h2>${services.map(s=>link(s.path,s.name)).join('')}</div><div><h2>Where we work</h2>${cities.map(c=>link(c.path,c.name+', CO')).join('')}</div><div><h2>Plan your project</h2>${[...nav.slice(2),['Contact',paths.contact]].map(([label,path])=>link(path,label)).join('')}</div></div><div class="container footer-bottom"><p>© ${new Date().getUTCFullYear()} ${e(site.legalName)}</p><div>${link(paths.privacy,'Privacy')}${link(paths.accessibility,'Accessibility')}${link(paths.sitemap,'Sitemap')}</div></div></footer></body></html>`;
}

export function renderService(s) {
  const locals=localServices.filter(l=>l.service===s.id);
  const page={...s,type:'service',heading:s.heading||s.name,breadcrumbs:[['Services',paths.services],[s.name,s.path]]};
  const body=`<div class="container">${breadcrumb(page.breadcrumbs)}${intro('Residential construction · Denver Metro',page.heading,s.intro)}<div class="article-layout"><div><div class="option-strip">${list(s.options)}</div>${s.sections.map((item,i)=>sections([item])+(i===0?motionFigure(serviceVideo[s.id]):'')).join('')}${detailPair(s.id)}${s.id==='aging'?sourceLinks(['ada']):''}${faq(s.faqs)}</div>${sidebar(s.sections)}</div><section class="section"><div class="section-heading"><p class="eyebrow">Around Denver Metro</p><h2>Find your community.</h2></div>${cityCards()}${locals.length?`<div class="local-links"><h3>${e(s.name)} in your city</h3>${locals.map(l=>link(l.path,`${s.name} in ${cityById[l.city].name}`)).join('')}</div>`:''}</section><section class="section"><div class="section-heading"><p class="eyebrow">Plan with more clarity</p><h2>Useful reading before you start.</h2></div>${guideCards(s.guides)}</section>${contactBand()}</div>`;
  return {page,html:shell(page,body)};
}

export function renderCity(c) {
  const page={...c,type:'city',heading:`Home Remodeling in ${c.name}, CO`,breadcrumbs:[['Service areas',paths.areas],[c.name,c.path]]};
  const locals=localServices.filter(l=>l.city===c.id);
  const body=`<div class="container">${breadcrumb(page.breadcrumbs)}${intro(c.eyebrow,page.heading,c.intro)}${c.callout?`<aside class="notice"><h2>Start with the address.</h2><p>${e(c.callout)}</p>${link(source.address[1],'Check municipal status ↗','text-link')}</aside>`:''}<div class="article-layout"><div>${photoSections(c.sections,['framing','whiteKitchen','windowDone','peninsula','backyard','framingWide'][cities.indexOf(c)])}${faq([[c.question,c.answer]])}${sourceLinks(c.sources)}</div>${sidebar(c.sections)}</div><section class="section"><div class="section-heading"><p class="eyebrow">Built around your priorities</p><h2>Our services in ${e(c.name)}.</h2><p>Start with an addition or major remodel, or focus on the room that matters most.</p></div>${serviceCards()}${locals.length?`<div class="local-links"><h3>Explore a specific project in ${e(c.name)}</h3>${locals.map(l=>link(l.path,`${serviceById[l.service].name} in ${c.name}`)).join('')}</div>`:''}</section><section class="section"><div class="section-heading"><p class="eyebrow">Your planning library</p><h2>A more informed first step.</h2></div>${guideCards(c.guides)}</section>${contactBand()}</div>`;
  return {page,html:shell(page,body)};
}

export function renderLocal(l) {
  const c=cityById[l.city],s=serviceById[l.service];
  const heading=`${s.name} in ${c.name}, CO`;
  const page={...l,type:'local-service',title:(l.title||heading+' | Summit Custom Builders'),heading,description:l.description||l.intro,breadcrumbs:[['Service areas',paths.areas],[c.name,c.path],[s.name,l.path]]};
  const body=`<div class="container">${breadcrumb(page.breadcrumbs)}${intro('A project plan for your community',heading,l.intro)}<div class="article-layout"><div>${photoSections(l.sections,servicePhotos[s.id][0])}${detailPair(s.id)}<section class="prose-section"><h2>Discuss the scope and the next step</h2><p>Bring your project address, the changes you have in mind, and any existing plans. We can discuss construction needs, your priorities, and what information is needed before an estimate.</p>${link(s.path,'Explore the full '+s.name.toLowerCase()+' service','text-link')} ${link(c.path,'All remodeling services in '+c.name,'text-link')}</section>${faq([[c.question,c.answer]])}${sourceLinks(c.sources)}</div>${sidebar(l.sections,s)}</div><section class="section"><div class="section-heading"><p class="eyebrow">Read before you renovate</p><h2>Plan the details.</h2></div>${guideCards(s.guides.slice(0,3))}</section>${contactBand()}</div>`;
  return {page,html:shell(page,body)};
}

export function renderGuide(g) {
  const s=serviceById[g.service];
  const page={...g,breadcrumbs:[['Resources',paths.resources],[g.title,g.path]]};
  const body=`<div class="container">${breadcrumb(page.breadcrumbs)}${intro(g.legacy?'From the Summit library':'The homeowner’s field guide',g.title,g.intro)}<p class="byline">By ${e(g.author)} · Updated <time datetime="${g.date}">September 11, 2026</time>${g.originalDate?` · Originally published <time datetime="${g.originalDate}">${e(g.originalDate)}</time>`:''}</p><div class="article-layout"><article>${photoSections(g.sections,guidePhoto(g))}${g.checklist?`<section class="planning-checklist"><h2>Bring these questions to your consultation</h2>${list(g.checklist)}</section>`:''}${sourceLinks(g.sources)}<section class="article-next"><p class="eyebrow">Put the plan into motion</p><h2>Discuss your ${e(s.name.toLowerCase())} project.</h2><p>Bring your goals and your address. We can discuss the construction involved and what to explore next.</p>${link(s.path,'Explore '+s.name,'text-link')}${cta()}</section></article>${sidebar(g.sections,s)}</div><section class="section"><h2>Keep planning.</h2>${guideCards(guides.filter(x=>x.service===g.service&&x.id!==g.id).slice(0,3).map(x=>x.id))}</section></div>`;
  return {page,html:shell(page,body)};
}

export function renderCompanyPages() {
  const result=[];
  const add=(key,title,description,body,extra={})=>{const page={path:paths[key],title,description,type:'company',...extra};result.push({page,html:shell(page,body)});};
  const wrapped=(title,desc,body,eyebrow='Summit Custom Builders')=>`<div class="container">${intro(eyebrow,title,desc)}${body}</div>`;
  add('home','Denver Remodeling Contractor | Summit Custom Builders','Stay in the home you love. Summit Custom Builders plans and builds home additions, major remodels, kitchens, and bathrooms across Denver Metro.',
    `${scrollHero()}<div class="container" id="home-content" tabindex="-1">
    <div class="service-line"><span>Denver</span><span>Arvada</span><span>Wheat Ridge</span><span>Lakewood</span><span>Morrison</span><span>Golden</span></div>
    <section class="section"><div class="section-heading split-heading"><div><p class="eyebrow">A home that fits your life</p><h2>Build on what<br>you already love.</h2></div><p>Keep the place that matters to you. Change the spaces that no longer work. We connect the big picture to the construction details.</p></div>${serviceCards()}</section>
    ${galleryPreview()}<section class="local-feature"><div><p class="eyebrow">Good planning starts locally</p><h2>Your address changes<br>the questions to ask.</h2><p>The permitting authority, site conditions, and utility providers can shape a project before a floor plan is drawn. Explore practical considerations for your community.</p>${link(paths.areas,'Explore our service areas ↗','text-link')}</div><div class="city-list">${cities.map(c=>`<a href="${c.path}"><span>${c.name}</span><span aria-hidden="true">↗</span></a>`).join('')}</div></section>
    <section class="section"><div class="section-heading"><p class="eyebrow">Clarity before construction</p><h2>Start with better questions.</h2><p>Practical guides to scope, budgets, timelines, and the details behind a well-planned remodel.</p></div>${guideCards(['planning-addition','addition-cost','whole-home-plan'])}${link(paths.resources,'Visit the remodeling resource library ↗','text-link')}</section>${contactBand()}</div>`);
  add('services','Home Remodeling Services in Denver | Summit Custom Builders','Explore home additions, major renovations, kitchens, bathrooms, general contracting, and aging-in-place remodeling across Denver Metro.',wrapped('Home remodeling services for every chapter.','Start with what you want to change. Our six services connect the big construction decisions to the spaces you use every day.',`${serviceShowcase()}${galleryPreview()}<section class="prose-section"><h2>One room or a connected project?</h2><p>If your plans involve several rooms, start with home remodeling. If you need more space beyond the existing layout, explore an addition. Kitchens, bathrooms, and accessibility improvements can stand alone or become part of that larger project.</p>${link(paths.process,'See how to prepare for the process ↗','text-link')}</section>${contactBand()}`));
  add('areas','Denver Remodeling Service Areas | Summit Custom Builders','Serving Denver, Arvada, Wheat Ridge, Lakewood, Morrison, and Golden with home additions, major remodels, kitchens, bathrooms, and aging-in-place renovations.',wrapped('Denver remodeling service areas.','We offer all six services across these communities. Explore the planning questions that matter in each place.',`<section class="section compact">${cityCards()}</section><div class="area-photo-pair">${photoFigure('framingWide',{sizes:'(max-width: 650px) calc(100vw - 42px), 720px'})}${photoFigure('island',{sizes:'(max-width: 650px) calc(100vw - 42px), 600px'})}</div><aside class="notice"><h2>Mailing city and building jurisdiction can differ.</h2><p>For Jefferson County addresses, check municipal status before selecting a permit checklist. Confirm the result and your proposed scope with the relevant authority.</p>${link(source.address[1],'Use Jefferson County’s address lookup ↗','text-link')}</aside>${contactBand()}`));
  add('about','About Summit Custom Builders | Denver Remodeler','Meet Summit Custom Builders: a Denver-based construction company focused on clear communication, personal involvement, and homes that fit everyday life.',wrapped('About Summit Custom Builders.','Your house holds routines, relationships, and plans for the future. The work should begin by understanding them.',`<div class="article-layout"><div class="prose">${photoFigure('framingMaterials',{className:'article-photo'})}${sections([
    ['A Denver company with a personal approach','Summit Custom Builders, Inc. is based in Denver and serves homeowners in Denver, Arvada, Wheat Ridge, Lakewood, Morrison, and Golden. Owner Richard P. Fleenor Jr., known as Rick, is identified in the company’s public business profile. Our work includes additions, remodeling, kitchens, bathrooms, and changes that help a home serve its occupants over time.'],
    ['Communication, construction, completion','The company’s longstanding approach centers on listening, coordinating construction, and staying involved as a project takes shape. A clear conversation about scope, priorities, and responsibilities provides a foundation for the work that follows.'],
    ['The details belong in the conversation','Ask about relevant project experience, the roles involved, material purchasing, updates, and the way changes will be handled. Current credentials and requirements should be checked for the property and scope. We can discuss references and project information as part of your consultation.']
  ])}<section class="prose-section"><h2>Read independent business information</h2><p>Review the company profile and customer feedback, then bring your questions to a conversation about your own project.</p>${link('https://www.bbb.org/us/co/denver/profile/remodel-contractors/summit-custom-builders-inc-1296-90268965','View Summit’s BBB profile ↗','text-link')}</section></div>${sidebar([['A Denver company with a personal approach'],['Communication, construction, completion'],['The details belong in the conversation']])}</div>${contactBand()}`));
  const process=[['Share the goals','Start with the address, the changes you need, and any available plans. Explain the timing and household constraints that matter. The initial conversation helps establish the project and what information is needed next.'],['Establish the scope','Discuss measurements, design, engineering, existing conditions, and the property’s approval requirements. Identify who is responsible for each part. The specific project determines which professional services are needed.'],['Align the estimate and decisions','Review inclusions, exclusions, allowances, material choices, and the proposed sequence. Agree on purchasing responsibility, how changes are documented, and the arrangements for living around construction.'],['Coordinate construction','Construction connects trades, materials, inspections, and the work at the existing home. Confirm communication expectations and keep decisions documented as the project progresses.'],['Complete the handoff','Use the project agreement to define completion, walkthroughs, remaining items, relevant inspection closeout, and product or warranty information. Keep the records together for future questions.']];
  add('process','Home Remodeling Process in Denver | Summit Custom Builders','Prepare for consultation, scope, estimating, construction, and completion with Summit Custom Builders. Understand the questions to resolve at each stage.',wrapped('Our Denver home remodeling process.','These are the conversations that connect a project. Your scope and agreement establish the specific steps and responsibilities.',`<div class="process-visual-layout"><ol class="process-list">${process.map(([title,text],i)=>`<li><span class="step-number">0${i+1}</span><div><h2>${title}</h2><p>${text}</p></div></li>`).join('')}</ol><aside class="process-deck" aria-label="Construction and finish details">${['framingMaterials','framingWide','quartz','backyard','island'].map((id,i)=>photoFigure(id,{className:'process-frame',caption:photos[id].caption,sizes:'(max-width: 800px) calc(100vw - 42px), 650px'})).join('')}</aside></div><section class="process-film"><div class="section-heading"><h2>A closer look at construction.</h2></div>${motionFigure('framing',{id:'construction-film'})}</section>${contactBand()}`));
  add('projects','Denver Remodeling Projects | Summit Custom Builders','Explore kitchens, bathrooms, construction, and finish details from the Summit Custom Builders photo collection.',wrapped('Denver remodeling projects.','Construction details and finished spaces from Summit’s existing project gallery.',`${galleryMarkup()}<section class="original-gallery project-showcase" id="more-spaces"><div class="showcase-stage"><div class="section-heading"><p class="eyebrow">Another look inside</p><h2>More spaces. More details.</h2></div><div class="gallery gallery-updated">${projectDetailPhotos.map(id=>photoFigure(id,{sizes:'(max-width: 600px) calc(100vw - 42px), (max-width: 800px) 44vw, 600px'})).join('')}</div></div></section><section class="prose-section"><h2>Talk through a comparable project</h2><p>Tell us about the work you are considering. Ask about relevant experience, references, and the construction details behind a similar scope.</p></section>${contactBand()}`));
  add('resources','Denver Remodeling Resources | Summit Custom Builders','Helpful guides to home additions, remodeling budgets, construction timelines, contractor selection, and local planning in Denver Metro.',wrapped('Denver remodeling guides and resources.','A practical library for homeowners considering an addition, a major renovation, or a more usable room.',`<form class="resource-filter" role="search"><label for="resource-search">Find a guide</label><input id="resource-search" type="search" placeholder="Search budgets, permits, kitchens…" autocomplete="off"><label for="resource-topic">Topic</label><select id="resource-topic"><option value="">All topics</option>${services.map(s=>`<option value="${s.id}">${e(s.name)}</option>`).join('')}</select><button class="button" type="submit">Find guides</button></form><p id="resource-count" class="small" aria-live="polite">${guides.length+legacyArticles.length} guides and articles</p><div class="card-grid resource-grid">${[...guides,...legacyArticles].map(g=>`<div class="resource-item" data-topic="${g.service}" data-search="${e((g.title+' '+g.intro).toLowerCase())}">${card(g.path,g.title,g.intro,'Read guide',guidePhoto(g))}</div>`).join('')}</div><p id="no-resources" hidden>No guides match that search. Try a broader term or choose all topics.</p>${contactBand()}`));
  add('contact','Denver Remodeling Consultation | Summit Custom Builders','Tell Summit Custom Builders about your addition or renovation in Denver Metro. Call 720-431-1056 or send a project inquiry.',wrapped('Start your Denver remodeling consultation.','A little about your home. A little about what you need. That’s enough to start a useful conversation.',`<div class="contact-layout"><div>${renderForm()}</div><aside class="contact-details">${photoFigure('island',{className:'contact-photo',caption:'A place for your next chapter.',sizes:'(max-width: 800px) calc(100vw - 92px), 360px'})}<p class="eyebrow">Prefer to talk?</p><h2>${link('tel:'+site.tel,site.phone)}</h2><p>Summit Custom Builders, Inc.<br>825 S. Yates St.<br>Denver, CO 80219</p><h3>Before you send</h3><p>Include the city and the spaces involved. You do not need finished drawings to start the conversation.</p><h3>Our service area</h3><p>Denver, Arvada, Wheat Ridge, Lakewood, Morrison, and Golden.</p></aside></div>`));
  add('privacy','Privacy Policy | Summit Custom Builders','How this website handles project inquiries, contact details, and basic referral information.',wrapped('Privacy policy','Updated September 11, 2026.',`<div class="prose narrow">${sections([
    ['Information you provide','The consultation form collects your name, email address, optional phone number, project city, project type, optional timing, and project description. Please do not send sensitive medical, financial, or identification information.'],
    ['How inquiry information is used','Information is used to receive and respond to your project inquiry and understand the services and communities receiving interest. Inquiries are stored on the website’s server. When a delivery integration is configured, they may also be sent to the business’s designated inquiry system and its service providers.'],
    ['Referral information and browser storage','This site uses session storage, when available, to remember the first page visited and the referring website’s hostname during your visit. These fields may accompany a submitted inquiry. It does not store your form message in browser storage or load advertising trackers. The server may use connection information temporarily to limit abusive submissions. Hosting infrastructure may maintain access logs.'],
    ['Questions or removal requests','Call 720-431-1056 to ask about information you have submitted, request a correction, or request deletion. Inquiries should be retained only as needed to respond, manage the potential project, and meet applicable recordkeeping needs. Do not use this public form to transmit highly sensitive information.'],
    ['Links to other websites','Official resources and business profiles linked from this site have their own privacy practices. Review those websites’ policies when using their services.']
  ])}</div>`),{noindex:true});
  add('accessibility','Accessibility Statement | Summit Custom Builders','Accessibility features of the Summit Custom Builders website and how to request help with project information.',wrapped('Accessibility statement','We want project information and the inquiry process to be usable by as many people as possible.',`<div class="prose narrow">${sections([
    ['Using the site','Pages use readable text, semantic headings, keyboard-accessible links and controls, visible focus states, and text labels on form fields. Core content and the consultation form are available without JavaScript. Layouts adapt to smaller screens and enlarged text.'],
    ['Request help or report a barrier','If you cannot use part of the website, call 720-431-1056. Tell us which page or task is causing difficulty and what alternative would help. You can also use the contact form if it is accessible to you.'],
    ['Ongoing improvement','Accessibility is an ongoing effort. This statement does not claim a third-party certification. External websites linked from the resource pages operate independently.']
  ])}${link(paths.contact,'Contact Summit','text-link')}</div>`),{noindex:true});
  add('thanks','Inquiry Received | Summit Custom Builders','Your consultation request has been recorded. Call Summit Custom Builders at 720-431-1056 for a direct conversation.',wrapped('Thank you for sharing your plans.','Your inquiry has been recorded.',`<div class="prose narrow"><p>If you need to speak with us directly, call ${link('tel:'+site.tel,site.phone)}. You can keep exploring the planning guides while you consider your next steps.</p>${link(paths.resources,'Explore the planning guides ↗','button')}</div>`),{noindex:true});
  return result;
}

export function renderSitemap(pages) {
  const page={path:paths.sitemap,title:'Sitemap | Summit Custom Builders',description:'Browse Summit Custom Builders services, cities, project information, and remodeling resources.',type:'utility',noindex:true};
  const groups=[['Start here',['company']],['Services',['service']],['Communities',['city']],['Local services',['local-service']],['Guides & articles',['guide']]];
  return {page,html:shell(page,`<div class="container">${intro('Explore the website','Find your next step.','Every service, community, and planning guide in one place.')}<div class="sitemap-groups">${groups.map(([label,types])=>`<section><h2>${label}</h2><ul>${pages.filter(p=>types.includes(p.type)&&!p.noindex).map(p=>`<li>${link(p.path,p.title.replace(/ \|.*$/,''))}</li>`).join('')}</ul></section>`).join('')}</div></div>`)};
}

export function render404() { const page={path:'/404/',title:'Page Not Found | Summit Custom Builders',description:'Find services, city information, or contact Summit Custom Builders.',noindex:true};return shell(page,`<div class="container">${intro('Page not found','Let’s get you back on track.','This address does not lead to a page. Explore our services or contact us about your project.')}<div class="hero-actions">${link(paths.services,'Explore services','button')}${link(paths.contact,'Contact Summit','text-link')}</div></div>`); }
